FROM polyaxon/polyaxon-base

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

RUN apt-get -y update && \
    apt-get -y install git

COPY requirements /requirements

RUN pip3 install --no-cache-dir -r /requirements/requirements-base.txt
