FROM polyaxon/base:3

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

ENV TENSORFLOW_VERSION 1.3.0

# Install TensorFlow GPU version from central repo
RUN pip3 --no-cache-dir install tensorflow==${TENSORFLOW_VERSION}
