FROM polyaxon/polyaxon-core

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

ENV POLYAXON_SERVICE=sidecar

WORKDIR /polyaxon
COPY . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/sidecar/requirements-dev.txt

ENTRYPOINT ["python3", "polyaxon/manage.py", "start_sidecar"]
