FROM polyaxon/polyaxon-base

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

COPY requirements /requirements

VOLUME /polyaxon
WORKDIR /polyaxon
copy . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/side/requirements-dev.txt
WORKDIR /polyaxon

ENTRYPOINT ["python3", "polyaxon/manage.py", "start_sidecar"]
