FROM polyaxon/base:2

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

ENV TENSORFLOW_VERSION 1.4.0

# Install TensorFlow CPU version from central repo
RUN pip --no-cache-dir install tensorflow==${TENSORFLOW_VERSION}
