FROM polyaxon/polyaxon-base

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

COPY requirements /requirements

VOLUME /polyaxon
WORKDIR /polyaxon
copy . /polyaxon

RUN apt-get -y update && \
    apt-get -y install git

RUN pip3 install --no-cache-dir -r /requirements/commands/requirements-dev.txt

ENTRYPOINT ["python3", "polyaxon/manage.py"]
