FROM polyaxon/polyaxon-base

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

COPY requirements /requirements

VOLUME /polyaxon
WORKDIR /polyaxon
copy . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/crons/requirements-dev.txt
WORKDIR /polyaxon/polyaxon
ENTRYPOINT ["celery", "-A", "polyaxon", "beat", "--loglevel=INFO"]
