FROM polyaxon/polyaxon-core

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

COPY requirements /requirements

VOLUME /polyaxon
WORKDIR /polyaxon
copy . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/monitor_resources/requirements-dev.txt
WORKDIR /polyaxon

ENTRYPOINT ["python3", "polyaxon/manage.py",  "monitor_statuses"]
