FROM polyaxon/polyaxon-base

MAINTAINER mourad mourafiq <mouradmourafiq@gmail.com>

RUN apt-get -y update && \
    apt-get -y install git

COPY requirements /requirements
WORKDIR /polyaxon
COPY . /polyaxon

RUN pip3 install --no-cache-dir -r /requirements/streams/requirements-dev.txt

WORKDIR /polyaxon/polyaxon

ENTRYPOINT ["python3", "-m", "sanic", "streams.api.app", "--host=0.0.0.0", "--port=1337"]
